// Site qualification of the native image optimizer: builds a disposable EmDash site from the patched
// pilot host (Node adapter, SQLite, local storage, `safeMedia`), registers the plugin, and drives it
// over HTTP as a signed-in admin. It checks apply, restore, re-optimization, bulk runs, delivery
// freshness, authorization, the plugin lifecycle (upgrade, disable, re-enable, uninstall, reinstall),
// the sandboxed edition and the rollback through the host's recovery entry point.
//
//   node packages/image-optimizer/qualification/qualify-site.mjs --pilot <emdash-pilot worktree>
//     [--work <directory>] [--port <port>] [--patch-manifest <patches.json>] [--no-evidence]
//     [--runner process | --runner systemd --site-user <user> [--unit <name>] [--memory-max 3G]
//      [--cpu-quota 200%] [--build-wrapper <executable>]]
//
// Runners. `process` (the default) starts the site as a child of this script, as in a container.
// `systemd` is the hosted profile: run as root on the host, it starts the site as a transient systemd
// service under the site user, with the memory and CPU caps and the sandboxing in `systemd.mjs`, its
// data directories owned by that user with mode 0700, and checks those, the cgroup, the processor's
// workers and out-of-memory events besides everything else. Build steps can then run elsewhere
// through `--build-wrapper` (see `useBuildWrapper` in `site.mjs`); the site itself runs with the Node
// binary running this script.
//
// The site binds to 127.0.0.1 only. Every image is generated by Sharp, and the admin and editor
// sign in with in-memory software passkeys created for the run. Evidence is written beside this
// script only when every check passed: `site-latest.json` for the process runner,
// `site-host-latest.json` for the systemd runner, and `site-proxy-latest.json` or
// `site-host-proxy-latest.json` with `--proxy caddy`.
//
// Proxy. `--proxy caddy [--proxy-port <port>] [--proxy-image <image>]` starts a throwaway Caddy on
// 127.0.0.1 in front of the site (`proxy.mjs`: a `caddy` binary, or a container of the image on the
// host's network) and sends every request of the run to the proxy instead of the site's port. The
// site's URL and the passkeys' origin are then the proxy's. It checks besides that the proxy's
// configuration only passes requests on, and that every response measured came through it.
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { cpus, totalmem } from 'node:os';
import { join, relative, resolve } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { setTimeout as sleep } from 'node:timers/promises';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

import { createClient, expectOk, inviteUser, logIn, setUpSite } from './http.mjs';
import { build, buildSite, createSite, installedPluginVersion, installPlugin, packHost, packPlugin, startSite, useBuildWrapper } from './site.mjs';
import { assertPassThrough, startCaddy } from './proxy.mjs';
import { createSystemdRunner } from './systemd.mjs';

const here = fileURLToPath(new URL('.', import.meta.url));
const repository = resolve(here, '../../..');
const { values: args } = parseArgs({
  options: {
    pilot: { type: 'string', default: process.env.EMDASH_PILOT_DIR ?? join(repository, '.upstream/emdash-pilot') },
    work: { type: 'string', default: join(repository, '.qualification-runs/image-optimizer-site') },
    port: { type: 'string', default: '4410' },
    'patch-manifest': { type: 'string' },
    'no-evidence': { type: 'boolean', default: false },
    'reuse-packages': { type: 'boolean', default: false },
    runner: { type: 'string', default: 'process' },
    'site-user': { type: 'string' },
    unit: { type: 'string' },
    'memory-max': { type: 'string', default: '3G' },
    'cpu-quota': { type: 'string', default: '200%' },
    'build-wrapper': { type: 'string' },
    proxy: { type: 'string', default: 'none' },
    'proxy-port': { type: 'string' },
    'proxy-image': { type: 'string' },
  },
});

const PLUGIN = 'image-optimizer';
const API = `/_emdash/api/plugins/${PLUGIN}`;
const UPGRADE_VERSION = '0.1.1-qualification';
const work = resolve(args.work);
const paths = {
  packages: join(work, 'packages'),
  site: join(work, 'site'),
  logs: join(work, 'logs'),
  data: join(work, 'data'),
  database: join(work, 'data/site.db'),
  uploads: join(work, 'data/uploads'),
  private: join(work, 'data/private'),
  staging: join(work, 'data/staging'),
  sessions: join(work, 'data/sessions'),
};
if (!['none', 'caddy'].includes(args.proxy)) throw new Error(`Unknown proxy ${args.proxy}`);
const proxied = args.proxy === 'caddy';
const proxyPort = Number(args['proxy-port'] ?? Number(args.port) + 1);
/** Where the site listens, and where the run sends its requests: the proxy when there is one. */
const siteOrigin = `http://127.0.0.1:${Number(args.port)}`;
const origin = proxied ? `http://127.0.0.1:${proxyPort}` : siteOrigin;

if (!['process', 'systemd'].includes(args.runner)) throw new Error(`Unknown runner ${args.runner}`);
if (args.runner === 'systemd' && (!args['site-user'] || process.getuid() !== 0)) throw new Error('The systemd runner runs as root and needs --site-user');
if (args['build-wrapper']) useBuildWrapper(resolve(args['build-wrapper']));
const hosted =
  args.runner === 'systemd'
    ? createSystemdRunner({
        unit: args.unit ?? args['site-user'],
        user: args['site-user'],
        node: process.execPath,
        siteDirectory: paths.site,
        dataDirectory: paths.data,
        port: Number(args.port),
        logFile: join(paths.logs, 'site.log'),
        memoryMax: args['memory-max'],
        cpuQuota: args['cpu-quota'],
      })
    : null;

const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const started = Date.now();
const log = (message) => console.log(`[${((Date.now() - started) / 1000).toFixed(0).padStart(5)} s] ${message}`);

/** Each passed check, in order, with what it established. */
const checks = [];
function passed(name, details = {}) {
  checks.push({ name, ...details });
  log(`ok  ${name}`);
}

async function waitFor(what, probe, { timeoutMs = 240_000, intervalMs = 3_000 } = {}) {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const value = await probe();
    if (value) return value;
    if (Date.now() > deadline) throw new Error(`Timed out waiting for ${what}`);
    await sleep(intervalMs);
  }
}

// --- Site state: database rows and files -----------------------------------------------------

function database() {
  return new DatabaseSync(paths.database, { readOnly: true });
}

function query(sql, ...parameters) {
  const db = database();
  try {
    return db.prepare(sql).all(...parameters);
  } finally {
    db.close();
  }
}

function filesUnder(directory) {
  const out = {};
  const walk = (current) => {
    let entries;
    try {
      entries = readdirSync(current, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const path = join(current, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.isFile()) out[relative(directory, path)] = sha256(readFileSync(path));
    }
  };
  walk(directory);
  return out;
}

/**
 * What a refused request must not change: media rows, the host's revisions, originals and
 * operations, the plugin's storage, settings and key-value rows, its scheduled tasks, and every file
 * in public storage, the private originals store and the plugin's staging directory.
 */
function snapshot() {
  const db = database();
  try {
    const rows = (sql) => sha256(JSON.stringify(db.prepare(sql).all()));
    return {
      media: rows('SELECT * FROM media ORDER BY id'),
      revisions: rows('SELECT * FROM _emdash_media_revisions ORDER BY id'),
      originals: rows('SELECT * FROM _emdash_media_originals ORDER BY sha256'),
      operations: rows('SELECT * FROM _emdash_media_operations ORDER BY operation_id'),
      pluginStorage: rows(`SELECT * FROM _plugin_storage WHERE plugin_id = '${PLUGIN}' ORDER BY collection, id`),
      pluginOptions: rows(`SELECT * FROM options WHERE name LIKE 'plugin:${PLUGIN}:%' ORDER BY name`),
      cron: rows(`SELECT id, plugin_id, task_name, schedule, enabled, status FROM _emdash_cron_tasks WHERE plugin_id = '${PLUGIN}' ORDER BY id`),
      uploads: sha256(JSON.stringify(filesUnder(paths.uploads))),
      private: sha256(JSON.stringify(filesUnder(paths.private))),
      staging: sha256(JSON.stringify(filesUnder(paths.staging))),
    };
  } finally {
    db.close();
  }
}

function changedParts(before, after) {
  return Object.keys(before).filter((key) => before[key] !== after[key]);
}

function mediaRow(id) {
  return query('SELECT * FROM media WHERE id = ?', id)[0];
}

function activeRevision(id) {
  return query('SELECT r.* FROM media m JOIN _emdash_media_revisions r ON r.id = m.revision_id WHERE m.id = ?', id)[0] ?? null;
}

function operations(id) {
  return query('SELECT operation_id, kind, state, expected_revision_id, candidate_revision_id, candidate_sha256, original_sha256 FROM _emdash_media_operations WHERE media_id = ? ORDER BY created_at, operation_id', id);
}

function pluginRows() {
  return query(`SELECT collection, COUNT(*) AS count FROM _plugin_storage WHERE plugin_id = '${PLUGIN}' GROUP BY collection ORDER BY collection`);
}

// --- Delivery ----------------------------------------------------------------------------------

const fileUrl = (key) => `/_emdash/api/media/file/${key}`;
const transformedUrl = (key) => `/_image?href=${encodeURIComponent(fileUrl(key))}&w=320&f=png`;

async function fetchBytes(path, init = {}) {
  const response = await fetch(`${origin}${path}`, { redirect: 'manual', ...init });
  const bytes = Buffer.from(await response.arrayBuffer());
  return {
    status: response.status,
    sha256: sha256(bytes),
    bytes,
    cacheControl: response.headers.get('cache-control'),
    etag: response.headers.get('etag'),
    lastModified: response.headers.get('last-modified'),
    via: response.headers.get('via'),
    age: response.headers.get('age'),
  };
}

/**
 * Requests the direct and transformed URLs right after a mutation answered, until each serves the
 * expected content: the direct URL the expected digest, the transformed URL something other than
 * its previous output (or exactly its earlier output, after a byte-exact restore).
 */
async function freshness(event, key, { directSha, directNot, transformedNot, transformedSha }) {
  const measure = async (path, fresh) => {
    const begin = performance.now();
    let stale = 0;
    for (;;) {
      const got = await fetchBytes(path);
      // Through the proxy, every response measured must have come through it.
      if (proxied) assert.match(got.via ?? '', /caddy/i, `${event}: ${path} was not answered through the proxy`);
      if (got.status === 200 && fresh(got)) {
        const measured = { staleResponses: stale, msToFresh: Number((performance.now() - begin).toFixed(1)), cacheControl: got.cacheControl, etag: got.etag, sha256: got.sha256 };
        return proxied ? { ...measured, via: got.via, age: got.age } : measured;
      }
      stale += 1;
      if (performance.now() - begin > 30_000) throw new Error(`${event}: ${path} still stale after 30 s (${stale} responses)`);
      await sleep(100);
    }
  };
  const direct = await measure(fileUrl(key), (got) => (directSha ? got.sha256 === directSha : got.sha256 !== directNot));
  const transformed = await measure(transformedUrl(key), (got) =>
    transformedSha ? got.sha256 === transformedSha : got.sha256 !== transformedNot,
  );
  return { event, direct, transformed };
}

const delivery = [];

// --- Fixtures ----------------------------------------------------------------------------------

/** Sharp-generated photograph-like JPEGs (gradient, texture and grain), saved heavier than needed. */
async function fixtures(sharp, count) {
  const images = [];
  for (let index = 0; index < count; index += 1) {
    const width = 1024;
    const height = 768;
    const hue = (index * 37) % 360;
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
      <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="hsl(${hue},70%,55%)"/><stop offset="1" stop-color="hsl(${(hue + 140) % 360},60%,35%)"/>
      </linearGradient></defs>
      <rect width="100%" height="100%" fill="url(#g)"/>
      <circle cx="${300 + index * 40}" cy="380" r="${150 + index * 5}" fill="hsl(${(hue + 60) % 360},80%,70%)" opacity="0.6"/>
    </svg>`;
    const grain = await sharp({ create: { width, height, channels: 3, noise: { type: 'gaussian', mean: 128, sigma: 18 } } }).raw().toBuffer();
    const bytes = await sharp(Buffer.from(svg))
      .composite([{ input: grain, raw: { width, height, channels: 3 }, blend: 'overlay' }])
      .jpeg({ quality: 100, chromaSubsampling: '4:4:4' })
      .toBuffer();
    images.push({ name: `fixture-${String(index + 1).padStart(2, '0')}.jpg`, bytes, width, height });
  }
  return images;
}

/**
 * Images near the processor's limits (24 MP and 16 MiB in, lossless WebP 12 MP), photograph-like
 * like the fixtures above. The grain is lowered until each file is under the input limit.
 */
async function heavyFixtures(sharp) {
  const limit = 15 * 1024 * 1024;
  const make = async ({ name, width, height, type, encode }) => {
    for (const grain of [12, 8, 5, 3, 0]) {
      const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
        <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stop-color="hsl(20,70%,55%)"/><stop offset="1" stop-color="hsl(200,60%,35%)"/>
        </linearGradient></defs>
        <rect width="100%" height="100%" fill="url(#g)"/>
        <circle cx="${width / 3}" cy="${height / 2}" r="${height / 3}" fill="hsl(90,80%,70%)" opacity="0.6"/>
      </svg>`;
      let image = sharp(Buffer.from(svg), { limitInputPixels: false });
      if (grain > 0) {
        const noise = await sharp({ create: { width, height, channels: 3, noise: { type: 'gaussian', mean: 128, sigma: grain } } }).raw().toBuffer();
        const raw = await image.composite([{ input: noise, raw: { width, height, channels: 3 }, blend: 'overlay' }]).removeAlpha().raw().toBuffer();
        image = sharp(raw, { raw: { width, height, channels: 3 } });
      }
      const bytes = await encode(image);
      if (bytes.length <= limit) return { name, width, height, type, bytes };
    }
    throw new Error(`${name} does not fit under the input limit`);
  };
  return [
    await make({ name: 'near-limit-24mp.jpg', width: 6000, height: 3990, type: 'image/jpeg', encode: (image) => image.jpeg({ quality: 95 }).toBuffer() }),
    await make({ name: 'near-limit-12mp.webp', width: 4000, height: 2990, type: 'image/webp', encode: (image) => image.webp({ quality: 95 }).toBuffer() }),
    await make({ name: 'near-limit-12mp-lossless.webp', width: 4000, height: 2990, type: 'image/webp', encode: (image) => image.webp({ lossless: true }).toBuffer() }),
  ];
}

// --- Site lifecycle ------------------------------------------------------------------------------

let site = null;
let proxy = null;
/** The profile the host reports, read from the plugin's refusal while nothing is allowed. */
let qualifiedProfile = null;
/** The profile the media host adapter qualifies by default; the host must report exactly this. */
const SHIPPED_PROFILE = { runtime: 'node', database: 'sqlite', storage: 'local', locks: 'in-process' };

function siteConfig(edition) {
  return {
    edition,
    // First an explicitly empty list, which must keep the plugin read-only. Once the host's profile
    // is known, no list at all: the plugin as shipped, with the adapter's default list.
    ...(qualifiedProfile ? {} : { qualifiedProfiles: [] }),
    stagingDirectory: paths.staging,
    origin,
    databasePath: paths.database,
    uploadsDirectory: paths.uploads,
    privateDirectory: paths.private,
    // Under systemd the site's code is read-only, so Astro's sessions live with the data.
    ...(hosted ? { sessionsDirectory: paths.sessions } : {}),
  };
}

async function restartAs(edition, label) {
  await stopSite();
  await buildSite(paths.site, siteConfig(edition));
  site = hosted ? await hosted.start() : await startSite(paths.site, { port: Number(args.port), logFile: join(paths.logs, 'site.log') });
  if (hosted) checkUnit(label);
  log(`site started: ${label}`);
}

/** Memory events of each systemd unit the run started, read just before it stopped. */
const unitMemory = [];

async function stopSite() {
  const stopped = site ? await site.stop() : null;
  site = null;
  if (stopped?.memory) {
    unitMemory.push(stopped.memory);
    assert.equal(stopped.memory.events.oom ?? 0, 0, `the unit reached its memory limit: ${JSON.stringify(stopped.memory)}`);
    assert.equal(stopped.memory.events.oom_kill ?? 0, 0, `the kernel killed a process of the unit: ${JSON.stringify(stopped.memory)}`);
  }
}

// --- The hosted profile: the unit, its cgroup, its processes and its data ------------------------

/**
 * On each start under systemd: the caps are the kernel's for the unit's cgroup, and exactly one site
 * server runs, in that cgroup, as the site user.
 */
function checkUnit(label) {
  const cgroup = hosted.cgroup();
  assert.equal(cgroup.memoryMax, hosted.expected.memoryMax, `${label}: memory.max`);
  assert.equal(cgroup.swapMax, hosted.expected.swapMax, `${label}: memory.swap.max`);
  assert.equal(cgroup.cpuMax, hosted.expected.cpuMax, `${label}: cpu.max`);
  const servers = hosted.siteProcesses().filter((entry) => entry.role === 'server');
  assert.equal(servers.length, 1, `${label}: ${servers.length} site server processes`);
  assert.equal(servers[0].cgroup, cgroup.path, `${label}: the site server runs outside the unit's cgroup`);
  assert.equal(servers[0].pid, site.pid, `${label}: the site server is not the unit's main process`);
  const owner = /^Uid:\s+(\d+)\s+(\d+)/m.exec(readFileSync(`/proc/${servers[0].pid}/status`, 'utf8'));
  assert.deepEqual([Number(owner[1]), Number(owner[2])], [hosted.uid, hosted.uid], `${label}: the site server does not run as the site user`);
  return cgroup;
}

/** The processor's workers seen while sampling: there were some, and all ran in the unit's cgroup. */
function checkWorkers(label, seen) {
  const unitCgroup = hosted.cgroup().path;
  const workers = seen.filter((entry) => entry.role === 'worker');
  const outside = seen.filter((entry) => entry.cgroup !== unitCgroup);
  assert.ok(workers.length > 0, `${label}: no processor worker was seen`);
  assert.deepEqual(outside.map((entry) => ({ pid: entry.pid, role: entry.role, cgroup: entry.cgroup })), [], `${label}: site processes outside the unit's cgroup`);
  return { workersSeen: workers.length, processesSeen: seen.length };
}

/**
 * The data directory, the database and the private originals belong to the site user alone:
 * directories 0700, the database 0600 and every other file without group or other access, and
 * another unprivileged user can read none of them.
 */
function checkDataPermissions(label) {
  const { entries, problems } = hosted.inspectData();
  assert.deepEqual(problems, [], `${label}: data entries with the wrong owner or mode`);
  const mode = (path) => entries.find((entry) => entry.path === (relative(paths.data, path) || '.'))?.mode;
  assert.equal(mode(paths.database), 0o600, `${label}: database mode`);
  assert.equal(mode(paths.private), 0o700, `${label}: private directory mode`);
  assert.equal(mode(paths.data), 0o700, `${label}: data directory mode`);
  const privateFiles = Object.keys(filesUnder(paths.private)).map((path) => join(paths.private, path));
  const uploadFiles = Object.keys(filesUnder(paths.uploads)).map((path) => join(paths.uploads, path));
  const targets = [paths.data, paths.database, paths.private, paths.uploads, paths.staging, ...privateFiles.slice(0, 3), ...uploadFiles.slice(0, 3)];
  const attempts = hosted.readAsOtherUser(targets);
  const readable = Object.entries(attempts).filter(([, outcome]) => outcome !== 'EACCES');
  assert.deepEqual(readable, [], `${label}: another user could read site data`);
  return {
    entries: entries.length,
    files: entries.filter((entry) => !entry.directory).length,
    privateFiles: privateFiles.length,
    modes: Object.fromEntries(['data', 'database', 'private', 'uploads', 'staging'].map((name) => [name, mode(paths[name])?.toString(8) ?? null])),
    otherUser: hosted.otherUser,
    otherUserAttempts: Object.values(attempts).length,
    otherUserOutcomes: [...new Set(Object.values(attempts))],
  };
}

// --- Plugin calls --------------------------------------------------------------------------------

let admin;
let adminPasskey;

async function route(name, body, client = admin) {
  return expectOk(await client.post(`${API}/${name}`, body), name);
}

const blockAction = (actionId, value) => ({ type: 'block_action', action_id: actionId, page: '/report', value });

async function scanToCompletion(label) {
  const start = await route('scan-start', {});
  assert.equal(start.ok, true, `${label}: scan did not start: ${JSON.stringify(start)}`);
  const run = await waitFor(`${label} scan`, async () => {
    const status = expectOk(await admin.get(`${API}/scan-status`), 'scan-status');
    return status.run?.phase === 'complete' ? status.run : null;
  }, { timeoutMs: 300_000, intervalMs: 5_000 });
  return run;
}

async function bulkToCompletion(label, body) {
  const startedRun = await route('bulk-start', body);
  assert.equal(startedRun.ok, true, `${label}: run did not start: ${JSON.stringify(startedRun)}`);
  return waitFor(`${label} run`, async () => {
    const view = await route('bulk-status', {});
    return view.run?.runId === startedRun.run.runId && view.run.status === 'complete' ? view.run : null;
  }, { timeoutMs: 360_000, intervalMs: 5_000 });
}

function results() {
  return query(`SELECT id, data FROM _plugin_storage WHERE plugin_id = '${PLUGIN}' AND collection = 'results'`).map((row) => ({ id: row.id, ...JSON.parse(row.data) }));
}

// --- The run -------------------------------------------------------------------------------------

/** The commit of this checkout and whether it had changes when the run began, or null outside git. */
function sourceState() {
  try {
    const git = (...parameters) => build('git', parameters, { cwd: repository }).trim();
    // Evidence files an earlier run of this checkout wrote are not changes to what runs.
    const changed = git('status', '--porcelain').split('\n').filter((line) => line && !/qualification\/site(-host)?(-proxy)?-latest\.json$/.test(line));
    return { commit: git('rev-parse', 'HEAD'), uncommittedChanges: changed.length };
  } catch {
    return null;
  }
}
let source = null;

async function main() {
  if (!statSync(args.pilot, { throwIfNoEntry: false })?.isDirectory()) throw new Error(`No pilot worktree at ${args.pilot}; run pnpm host:pilot first.`);
  source = sourceState();
  const reuse = args['reuse-packages'] && statSync(join(paths.site, 'node_modules'), { throwIfNoEntry: false });
  if (reuse) {
    // A quicker repeat for development: same packages and site install, fresh data. Writes no evidence.
    for (const directory of [paths.data, paths.logs]) await rm(directory, { recursive: true, force: true });
  } else {
    await rm(work, { recursive: true, force: true });
  }
  for (const directory of [paths.packages, paths.logs]) await mkdir(directory, { recursive: true });
  if (hosted) {
    // The layout an operator prepares: one data directory for the site user, nothing for others.
    for (const directory of [paths.data, paths.uploads, paths.private, paths.staging, paths.sessions]) hosted.prepareDirectory(directory);
  } else {
    await mkdir(paths.uploads, { recursive: true });
  }

  // 1. Packages: the patched host, the plugin, and the plugin under a bumped version for the upgrade.
  const host = reuse ? reusedHost(resolve(args.pilot)) : packHost(resolve(args.pilot), paths.packages);
  let patches = null;
  if (args['patch-manifest']) {
    const manifest = JSON.parse(await readFile(args['patch-manifest'], 'utf8'));
    const last = manifest.patches.at(-1);
    assert.equal(host.tree, last.resultingTree, `The pilot tree ${host.tree} is not the tree of ${last.name}`);
    patches = manifest.patches.map((patch) => patch.name);
  }
  let plugin;
  if (reuse) {
    const { name, version } = JSON.parse(await readFile(join(repository, 'packages/image-optimizer/package.json'), 'utf8'));
    plugin = { name, version, current: join(paths.packages, `${name}-${version}.tgz`), upgradeVersion: UPGRADE_VERSION, upgraded: join(paths.packages, `${name}-${UPGRADE_VERSION}.tgz`) };
    installPlugin(paths.site, plugin.current);
  } else {
    plugin = await packPlugin(join(repository, 'packages/image-optimizer'), paths.packages, UPGRADE_VERSION);
    await createSite({ template: join(here, 'site'), siteDirectory: paths.site, hostTarball: host.tarball, pluginTarball: plugin.current });
  }
  passed('site packages built', { emdashCommit: host.commit, emdashTree: host.tree, patches, pluginVersion: plugin.version });
  const sharp = createRequire(join(paths.site, 'package.json'))('sharp');
  if (hosted) {
    // The site was installed by the build step; its native modules must load here, where it runs.
    const probe = await sharp({ create: { width: 64, height: 64, channels: 3, background: '#808080' } }).jpeg().toBuffer();
    assert.equal((await sharp(probe).metadata()).format, 'jpeg');
    passed('sharp loads where the site runs', { sharp: sharp.versions.sharp, libvips: sharp.versions.vips, glibc: process.report.getReport().header.glibcVersionRuntime ?? null });
  }

  if (proxied) {
    // The proxy stays up for the whole run; while the site restarts behind it, it answers 502.
    proxy = await startCaddy({
      proxyPort,
      sitePort: Number(args.port),
      directory: join(work, 'proxy'),
      image: args['proxy-image'] ?? null,
      name: `${args.unit ?? args['site-user'] ?? 'image-optimizer-qualification'}-proxy`,
      logFile: join(paths.logs, 'proxy.log'),
    });
    assertPassThrough(proxy.config, { proxyPort, sitePort: Number(args.port) });
    const unanswered = await fetch(`${origin}/_emdash/api/health`, { redirect: 'manual' });
    assert.equal(unanswered.status, 502, 'the proxy answered for a site that is not running');
    assert.match(unanswered.headers.get('server') ?? unanswered.headers.get('via') ?? '', /caddy/i);
    passed('the proxy only passes requests to the site', {
      proxy: proxy.name,
      version: proxy.version,
      listens: 'loopback only',
      handlers: proxy.config.handlers,
      upstreams: proxy.config.upstreams.length,
      fileSystemRoots: proxy.config.roots.length,
      adminEndpoint: proxy.config.admin,
      withoutTheSite: unanswered.status,
    });
  }

  // 2. Discovery: the native edition with an empty qualified list reports the host's profile and stays read-only.
  await restartAs('native', 'native edition, empty qualified list');
  ({ client: admin, passkey: adminPasskey } = await setUpSite(origin, { title: 'Image optimizer qualification', email: 'admin@example.test' }));
  const images = {};
  for (const fixture of await fixtures(sharp, 11)) {
    const form = new FormData();
    form.set('file', new Blob([fixture.bytes], { type: 'image/jpeg' }), fixture.name);
    const uploaded = expectOk(await admin.request('POST', '/_emdash/api/media', { form }), `upload ${fixture.name}`);
    images[fixture.name] = { ...uploaded.item, originalSha: sha256(fixture.bytes), originalBytes: fixture.bytes.length };
    const served = await fetchBytes(fileUrl(uploaded.item.storageKey));
    assert.equal(served.sha256, sha256(fixture.bytes));
  }
  const [A, B, C, D, E, F, G, H, I, J, K] = Object.values(images);
  passed('fixtures uploaded', { count: Object.keys(images).length, bytes: Object.values(images).map((image) => image.originalBytes) });

  if (hosted) {
    const cgroup = checkUnit('first start');
    passed('the unit runs the site under its caps', {
      properties: hosted.properties.map((property) => property.replace(paths.data, '<data directory>')),
      memoryMax: cgroup.memoryMax,
      swapMax: cgroup.swapMax,
      cpuMax: cgroup.cpuMax,
      serverInUnitCgroup: true,
      serverRunsAsSiteUser: true,
    });
    passed('site data belongs to the site user alone', checkDataPermissions('after uploads'));

    // One process per site: the runner refuses a second start, and systemd refuses a second unit
    // of the same name. Neither leaves a second process or disturbs the first.
    const pid = site.pid;
    const refusal = await hosted.start().then(
      () => null,
      (error) => error.message,
    );
    assert.ok(refusal?.includes('exactly one process'), `the runner started a second process: ${refusal}`);
    const duplicate = hosted.secondUnit();
    assert.notEqual(duplicate.status, 0, 'systemd started a second unit under the same name');
    const servers = hosted.siteProcesses().filter((entry) => entry.role === 'server');
    assert.deepEqual(servers.map((entry) => entry.pid), [pid], 'not exactly the one site process');
    assert.equal(hosted.state().MainPID, pid);
    assert.ok((await fetch(`${origin}/_emdash/api/health`)).status < 500);
    const unitName = new RegExp(hosted.unit.replaceAll('.', '\\.'), 'g');
    passed('a second process for the site is not started', {
      runnerRefusal: refusal.replace(unitName, '<unit>'),
      systemdRefusal: duplicate.stderr.split('\n')[0].replace(unitName, '<unit>'),
      serverProcesses: servers.length,
    });
  }

  const before = snapshot();
  const refused = await route('apply', { mediaId: A.id });
  assert.equal(refused.outcome, 'unavailable');
  assert.equal(refused.reason, 'unqualified-host');
  const described = /This host profile \(([^)]+)\)/.exec(refused.message)?.[1];
  assert.ok(described, refused.message);
  const reportedProfile = Object.fromEntries(described.split(', ').map((pair) => pair.split(' ')));
  const bulkRefused = await route('bulk-start', { kind: 'apply', mediaIds: [A.id] });
  assert.equal(bulkRefused.ok, false);
  assert.deepEqual(changedParts(before, snapshot()), []);
  assert.match(JSON.stringify(await route('admin', { type: 'page_load', page: '/report' })), /apply and restore are not available/);
  passed('an empty qualified list stays read-only', { reportedProfile, applyOutcome: refused.outcome, bulkStart: bulkRefused.error });

  // 3. The plugin as shipped, with no list given: the adapter's default list must allow exactly the
  // profile this host reports. Then a measured scan, sample, apply, restore, re-optimization, bulk.
  assert.deepEqual(reportedProfile, SHIPPED_PROFILE, 'the host does not report the profile the adapter qualifies');
  qualifiedProfile = reportedProfile;
  await restartAs('native', 'native edition as shipped, default qualified list');
  await logIn(admin, adminPasskey);
  assert.doesNotMatch(JSON.stringify(await route('admin', { type: 'page_load', page: '/report' })), /apply and restore are not available/);
  passed('the shipped default list allows the reported profile', { reportedProfile, qualifiedProfilesOption: 'not set' });

  const scanSampler = hosted?.sampleProcesses();
  const scan = await scanToCompletion('measured');
  const measured = results().filter((result) => result.basis === 'measured' && result.status === 'flagged');
  assert.equal(measured.length, Object.keys(images).length, `measured ${measured.length}: ${JSON.stringify(results().map((r) => [r.status, r.basis, r.reason]))}`);
  passed('measured scan', { totals: scan.totals, measuredFlagged: measured.length });
  if (hosted) passed('the processor workers run in the unit cgroup', checkWorkers('measured scan', scanSampler.stop()));

  if (hosted) {
    // A measured scan of images near the processor's limits, with a sample started beside it, under
    // the unit's caps and the processor limits as shipped: nothing is killed for memory.
    const heavy = await heavyFixtures(sharp);
    const heavyIds = [];
    for (const fixture of heavy) {
      const form = new FormData();
      form.set('file', new Blob([fixture.bytes], { type: fixture.type }), fixture.name);
      const uploaded = expectOk(await admin.request('POST', '/_emdash/api/media', { form }), `upload ${fixture.name}`);
      heavyIds.push(uploaded.item.id);
    }
    const sampler = hosted.sampleProcesses();
    const start = await route('scan-start', {});
    assert.equal(start.ok, true, `near-limit scan did not start: ${JSON.stringify(start)}`);
    // While the scan works, sample the largest image: at most two encodes, within the pixel budget.
    await waitFor('a worker of the near-limit scan', () => hosted.siteProcesses().some((entry) => entry.role === 'worker'), { timeoutMs: 120_000, intervalMs: 50 });
    const besideScan = await admin.post(`${API}/admin`, blockAction('sample_image', { mediaId: heavyIds[0] }));
    await waitFor('near-limit scan', async () => {
      const status = expectOk(await admin.get(`${API}/scan-status`), 'scan-status');
      return status.run?.phase === 'complete' ? status.run : null;
    }, { timeoutMs: 600_000, intervalMs: 2_000 });
    const workers = checkWorkers('near-limit scan', sampler.stop());
    const byId = new Map(results().map((result) => [result.id, result]));
    const outcomes = heavy.map((fixture, index) => {
      const result = byId.get(heavyIds[index]);
      return { name: fixture.name, megapixels: Number(((fixture.width * fixture.height) / 1e6).toFixed(1)), bytes: fixture.bytes.length, status: result?.status, basis: result?.basis, reason: result?.reason ?? null };
    });
    const cgroup = hosted.cgroup();
    assert.equal(cgroup.memoryEvents.oom ?? 0, 0, `memory.events: ${JSON.stringify(cgroup.memoryEvents)}`);
    assert.equal(cgroup.memoryEvents.oom_kill ?? 0, 0, `memory.events: ${JSON.stringify(cgroup.memoryEvents)}`);
    for (const outcome of outcomes) assert.ok(['flagged', 'ok'].includes(outcome.status) && outcome.basis === 'measured', `near-limit scan: ${JSON.stringify(outcome)}`);
    passed('a measured scan near the processor limits does not run out of memory under the caps', {
      images: outcomes,
      sampleBesideScan: { status: besideScan.status, refusedAsBusy: /busy/i.test(JSON.stringify(besideScan.body)) },
      ...workers,
      memoryMax: cgroup.memoryMax,
      memoryPeakBytes: cgroup.memoryPeakBytes,
      memoryEvents: cgroup.memoryEvents,
    });
  }

  // Editorial fields that apply and restore must keep.
  expectOk(await admin.put(`/_emdash/api/media/${A.id}`, { alt: 'A generated gradient', caption: 'Fixture for the site run', focalX: 0.25, focalY: 0.75 }), 'media update');
  const editorial = (row) => ({ id: row.id, storage_key: row.storage_key, alt: row.alt, caption: row.caption, focal_x: row.focal_x, focal_y: row.focal_y, width: row.width, height: row.height, filename: row.filename });
  const editorialBefore = editorial(mediaRow(A.id));

  const sampleBefore = snapshot();
  const sample = await route('admin', blockAction('sample_image', { mediaId: A.id }));
  const sampleText = JSON.stringify(sample);
  assert.match(sampleText, /Sample/);
  assert.deepEqual(changedParts(sampleBefore, snapshot()), []);
  passed('sample changes nothing', { mediaId: A.id });

  const transformedOriginal = (await fetchBytes(transformedUrl(A.storageKey))).sha256;
  assert.equal(mediaRow(A.id).revision_id, null, 'a revision before any safe-media operation');
  const applied = await route('apply', { mediaId: A.id });
  assert.equal(applied.outcome, 'optimized', JSON.stringify(applied));
  // Measured from the moment the route answered: the first request after it.
  delivery.push(await freshness('apply', A.storageKey, { directNot: A.originalSha, transformedNot: transformedOriginal }));
  const optimizedRevision = activeRevision(A.id);
  assert.equal(optimizedRevision.id, applied.revisionId);
  assert.notEqual(optimizedRevision.sha256, A.originalSha);
  assert.equal(delivery.at(-1).direct.sha256, optimizedRevision.sha256);
  // The host records the uploaded file as the baseline revision when it first replaces it.
  const originalRevision = query('SELECT * FROM _emdash_media_revisions WHERE id = ?', operations(A.id)[0].expected_revision_id)[0];
  assert.equal(originalRevision.kind, 'baseline');
  assert.equal(originalRevision.sha256, A.originalSha);
  assert.deepEqual(editorial(mediaRow(A.id)), editorialBefore);
  const servedOptimized = await fetchBytes(fileUrl(A.storageKey));
  assert.equal(servedOptimized.bytes.length, applied.outputBytes);
  passed('apply serves the new bytes at the same URL', {
    mediaId: A.id,
    url: fileUrl(A.storageKey),
    originalSha256: A.originalSha,
    servedSha256: servedOptimized.sha256,
    inputBytes: applied.inputBytes,
    outputBytes: applied.outputBytes,
    fromRevision: originalRevision.id,
    toRevision: optimizedRevision.id,
    editorialKept: Object.keys(editorialBefore),
  });

  // The original: kept privately, not in public storage, not reachable through any public route.
  // The host keeps the uploaded file as the baseline revision's object at its stable key in the
  // uploads directory; only the file route, which resolves the key to the active revision, keeps it
  // from being served. Recorded, so the docs can say the directory must not be served directly.
  const publicFiles = filesUnder(paths.uploads);
  const originalInUploads = Object.entries(publicFiles).filter(([, digest]) => digest === A.originalSha).map(([path]) => path);
  assert.ok(Object.values(filesUnder(paths.private)).includes(A.originalSha), 'The original is not in the private store');
  const original = query('SELECT storage_key FROM _emdash_media_originals WHERE sha256 = ?', A.originalSha)[0];
  assert.ok(original, 'No original record');
  const probes = [
    fileUrl(original.storage_key),
    fileUrl(encodeURIComponent(original.storage_key)),
    fileUrl(`..%2Fprivate%2F${encodeURIComponent(original.storage_key)}`),
    fileUrl(`../private/${original.storage_key}`),
    fileUrl(originalRevision.object_key ?? A.storageKey),
    `${fileUrl(A.storageKey)}?rev=${originalRevision.id}`,
    `${fileUrl(A.storageKey)}?revision=${originalRevision.id}`,
    `/_emdash/api/media/${A.id}`,
    transformedUrl(original.storage_key),
  ];
  for (const revision of query('SELECT object_key FROM _emdash_media_revisions WHERE media_id = ?', A.id)) {
    if (revision.object_key) probes.push(fileUrl(revision.object_key), transformedUrl(revision.object_key));
  }
  const probeResults = [];
  for (const path of probes) {
    const got = await fetchBytes(path);
    assert.notEqual(got.sha256, A.originalSha, `The original is served at ${path}`);
    probeResults.push({ path: path.replace(A.id, '<media>').replace(original.storage_key, '<original key>'), status: got.status });
  }
  // Where a web server or proxy that served files would expose them: the paths of the stored files
  // that hold the original, in the uploads directory and in the private store, under likely static
  // prefixes and as absolute paths. None may answer with the original.
  const storedOriginals = [
    ...originalInUploads.map((path) => join(paths.uploads, path)),
    ...Object.entries(filesUnder(paths.private)).filter(([, digest]) => digest === A.originalSha).map(([path]) => join(paths.private, path)),
  ];
  assert.ok(storedOriginals.some((path) => path.startsWith(paths.uploads)) && storedOriginals.some((path) => path.startsWith(paths.private)), 'the original is not stored in both directories');
  const staticPrefixes = ['', 'uploads', 'data/uploads', 'media', 'files', 'static', 'assets', 'public', 'private', 'data/private', 'originals', 'data', '_emdash/uploads', '_emdash/media'];
  const staticStatuses = {};
  let staticProbes = 0;
  for (const stored of storedOriginals) {
    const inData = relative(paths.data, stored);
    const inOwnDirectory = relative(stored.startsWith(paths.uploads) ? paths.uploads : paths.private, stored);
    const candidates = [
      ...staticPrefixes.flatMap((prefix) => [inOwnDirectory, inData].map((path) => `/${prefix ? `${prefix}/` : ''}${path}`)),
      stored,
      `/%2e%2e/%2e%2e${stored}`,
      `/..%2f..%2f${stored.slice(1)}`,
    ];
    for (const path of new Set(candidates)) {
      const got = await fetchBytes(path);
      assert.notEqual(got.sha256, A.originalSha, `The original is served at a static path (${staticProbes + 1})`);
      staticStatuses[got.status] = (staticStatuses[got.status] ?? 0) + 1;
      staticProbes += 1;
    }
  }
  if (hosted) passed('retained originals belong to the site user alone', checkDataPermissions('after apply'));
  passed('original not publicly reachable', {
    privateStoreHoldsOriginal: true,
    uploadsDirectoryHoldsOriginal: originalInUploads.map((path) => (path === A.storageKey ? '<stable key>' : '<other key>')),
    probes: probeResults,
    staticPathProbes: { storedCopies: storedOriginals.length, requests: staticProbes, statuses: staticStatuses, servedOriginal: 0 },
  });

  const restored = await route('restore', { mediaId: A.id });
  assert.equal(restored.outcome, 'restored', JSON.stringify(restored));
  delivery.push(await freshness('restore', A.storageKey, { directSha: A.originalSha, transformedSha: transformedOriginal }));
  const servedRestored = await fetchBytes(fileUrl(A.storageKey));
  assert.equal(servedRestored.sha256, A.originalSha);
  assert.equal(restored.sha256, A.originalSha);
  assert.deepEqual(editorial(mediaRow(A.id)), editorialBefore);
  passed('restore is byte-exact', { mediaId: A.id, servedSha256: servedRestored.sha256, revision: restored.revisionId });

  // Re-optimization under another preset reads the original privately; the original never becomes active.
  const reapplied = await route('apply', { mediaId: A.id });
  assert.equal(reapplied.outcome, 'optimized');
  const balancedRevision = activeRevision(A.id);
  const transformedBalanced = (await fetchBytes(transformedUrl(A.storageKey))).sha256;
  const opsBefore = operations(A.id).length;
  expectOk(await admin.put(`/_emdash/api/admin/plugins/${PLUGIN}/settings`, { values: { preset: 'high-fidelity' } }), 'settings');
  const reoptimized = await route('apply', { mediaId: A.id });
  assert.equal(reoptimized.outcome, 'optimized', JSON.stringify(reoptimized));
  delivery.push(await freshness('re-optimize', A.storageKey, { directNot: balancedRevision.sha256, transformedNot: transformedBalanced }));
  assert.equal(reoptimized.reoptimized, true);
  assert.equal(reoptimized.inputBytes, A.originalBytes, 're-optimization did not start from the original');
  const later = operations(A.id).slice(opsBefore);
  assert.deepEqual(later.map((operation) => operation.kind), ['replace']);
  assert.equal(later[0].expected_revision_id, balancedRevision.id, 'the re-optimization was not fenced on the optimized revision');
  const hiFiRevision = activeRevision(A.id);
  assert.notEqual(hiFiRevision.sha256, A.originalSha);
  assert.equal(delivery.at(-1).direct.sha256, hiFiRevision.sha256);
  passed('preset change re-optimizes from the original', {
    mediaId: A.id,
    preset: 'high-fidelity',
    inputBytes: reoptimized.inputBytes,
    outputBytes: reoptimized.outputBytes,
    fencedOn: balancedRevision.id,
    newRevision: hiFiRevision.id,
    hostOperationsSince: later.map((operation) => operation.kind),
  });
  const backToOriginal = await route('restore', { mediaId: A.id });
  assert.equal(backToOriginal.outcome, 'restored');
  assert.equal((await fetchBytes(fileUrl(A.storageKey))).sha256, A.originalSha);
  expectOk(await admin.put(`/_emdash/api/admin/plugins/${PLUGIN}/settings`, { values: { preset: 'balanced' } }), 'settings');

  const bulkApply = await bulkToCompletion('bulk apply', { kind: 'apply', mediaIds: [B.id, C.id, D.id] });
  assert.equal(bulkApply.counts.optimized, 3, JSON.stringify(bulkApply));
  for (const image of [B, C, D]) {
    const active = activeRevision(image.id);
    assert.notEqual(active.sha256, image.originalSha);
    assert.equal((await fetchBytes(fileUrl(image.storageKey))).sha256, active.sha256);
  }
  passed('bulk apply', { runId: bulkApply.runId, counts: bulkApply.counts, grossReductionBytes: bulkApply.grossReductionBytes });
  const bulkRestore = await bulkToCompletion('batch restore', { kind: 'restore', mediaIds: [B.id, C.id, D.id] });
  assert.equal(bulkRestore.counts.restored, 3, JSON.stringify(bulkRestore));
  for (const image of [B, C, D]) assert.equal((await fetchBytes(fileUrl(image.storageKey))).sha256, image.originalSha);
  passed('batch restore is byte-exact', { runId: bulkRestore.runId, counts: bulkRestore.counts });
  assert.deepEqual(filesUnder(paths.staging), {}, 'staging is not empty');

  // 4. Authorization: without a session, as an editor, without the CSRF header, cross-origin, with a bad token.
  const optimizedE = await route('apply', { mediaId: E.id });
  assert.equal(optimizedE.outcome, 'optimized');
  const editor = await inviteUser(admin, { email: 'editor@example.test', role: 40 });
  assert.equal(editor.user.role, 40);
  const anonymous = createClient(origin, { name: 'anonymous' });
  const calls = [
    ['sample', 'admin', blockAction('sample_image', { mediaId: A.id })],
    ['apply', 'apply', { mediaId: A.id }],
    ['restore', 'restore', { mediaId: E.id }],
    ['bulk-start apply', 'bulk-start', { kind: 'apply', mediaIds: [A.id, J.id] }],
    ['bulk-start restore', 'bulk-start', { kind: 'restore' }],
    ['bulk-retry', 'bulk-retry', {}],
    ['bulk-reconcile', 'bulk-reconcile', {}],
    ['scan-start', 'scan-start', {}],
  ];
  const callers = [
    ['no session', (path, body) => anonymous.post(path, body)],
    ['editor without plugins:manage', (path, body) => editor.client.post(path, body)],
    ['admin session without X-EmDash-Request', (path, body) => admin.post(path, body, { csrf: false })],
    ['admin session, cross-origin, no header', (path, body) => admin.post(path, body, { csrf: false, headers: { Origin: 'http://attacker.invalid' } })],
    // Forwarded headers a client sends must not make another origin look like the site's own.
    [
      'admin session, cross-origin with forged forwarded headers, no header',
      (path, body) =>
        admin.post(path, body, { csrf: false, headers: { Origin: 'http://attacker.invalid', 'X-Forwarded-Host': 'attacker.invalid', 'X-Forwarded-Proto': 'http', Forwarded: 'host=attacker.invalid;proto=http' } }),
    ],
    ['invalid bearer token', (path, body) => anonymous.post(path, body, { headers: { Authorization: 'Bearer ec_pat_invalid' } })],
  ];
  const matrix = [];
  for (const [callName, path, body] of calls) {
    for (const [callerName, call] of callers) {
      const prior = snapshot();
      const answer = await call(`${API}/${path}`, body);
      assert.ok([401, 403].includes(answer.status), `${callName} as ${callerName}: HTTP ${answer.status} ${JSON.stringify(answer.body).slice(0, 300)}`);
      assert.deepEqual(changedParts(prior, snapshot()), [], `${callName} as ${callerName} changed state`);
      matrix.push({ call: callName, caller: callerName, status: answer.status, code: answer.body?.error?.code ?? null });
    }
  }
  // Controls: the same admin, with the header, is allowed, also when it names the origin the run
  // uses as a browser would (the proxy's, with a proxy); the editor is signed in.
  assert.equal((await admin.post(`${API}/bulk-status`, {})).status, 200);
  assert.equal((await admin.post(`${API}/bulk-status`, {}, { headers: { Origin: origin } })).status, 200);
  assert.equal((await editor.client.get('/_emdash/api/auth/me')).status, 200);
  passed('unauthorized and CSRF-invalid requests are refused and change nothing', { requests: matrix.length, matrix });

  // 5. Lifecycle: a paused run survives an upgrade, then resumes.
  const paused = await route('bulk-start', { kind: 'apply', mediaIds: [F.id, G.id, H.id] });
  assert.equal(paused.ok, true);
  const pausedNow = await route('bulk-pause', {});
  assert.equal(pausedNow.ok, true, JSON.stringify(pausedNow));
  const beforeUpgrade = { results: results().length, plugin: pluginRows(), settings: query(`SELECT name, value FROM options WHERE name LIKE 'plugin:${PLUGIN}:settings:%' ORDER BY name`) };
  await stopSite();
  installPlugin(paths.site, plugin.upgraded);
  assert.equal(installedPluginVersion(paths.site), UPGRADE_VERSION);
  await restartAs('native', `upgraded to ${UPGRADE_VERSION}`);
  await logIn(admin, adminPasskey);
  const afterUpgrade = { results: results().length, plugin: pluginRows(), settings: query(`SELECT name, value FROM options WHERE name LIKE 'plugin:${PLUGIN}:settings:%' ORDER BY name`) };
  assert.deepEqual(afterUpgrade, beforeUpgrade);
  let view = await route('bulk-status', {});
  assert.equal(view.run.status, 'paused');
  const heldSnapshot = snapshot();
  await sleep(75_000); // more than one scheduler interval: nothing runs while paused
  view = await route('bulk-status', {});
  assert.equal(view.run.status, 'paused');
  // A tick may prepare a paused run (enqueue its items) but must not work on any image.
  assert.deepEqual(changedParts(heldSnapshot, snapshot()).filter((part) => !['cron', 'pluginStorage'].includes(part)), []);
  const pausedItems = query(`SELECT data FROM _plugin_storage WHERE plugin_id = '${PLUGIN}' AND collection = 'items' AND id LIKE ?`, `${paused.run.runId}:%`).map((row) => JSON.parse(row.data).state);
  assert.ok(pausedItems.every((state) => state === 'queued'), JSON.stringify(pausedItems));
  const eStillOptimized = activeRevision(E.id);
  assert.equal((await fetchBytes(fileUrl(E.storageKey))).sha256, eStillOptimized.sha256);
  assert.notEqual(eStillOptimized.sha256, E.originalSha);
  passed('upgrade keeps data and a paused run stays paused', { from: plugin.version, to: UPGRADE_VERSION, pluginRows: afterUpgrade.plugin, results: afterUpgrade.results, runId: paused.run.runId, itemsWhilePaused: pausedItems });

  assert.equal((await route('bulk-resume', {})).ok, true);
  const resumed = await waitFor('resumed run', async () => {
    const current = await route('bulk-status', {});
    return current.run.status === 'complete' ? current.run : null;
  }, { timeoutMs: 360_000, intervalMs: 5_000 });
  assert.equal(resumed.counts.optimized, 3, JSON.stringify(resumed));
  passed('the paused run resumes after the upgrade', { runId: resumed.runId, counts: resumed.counts });

  // Disable stops an active run; re-enabling continues it.
  const restoreRun = await route('bulk-start', { kind: 'restore', mediaIds: [F.id, G.id, H.id] });
  assert.equal(restoreRun.ok, true);
  expectOk(await admin.post(`/_emdash/api/admin/plugins/${PLUGIN}/disable`, {}), 'disable');
  const disabledCron = query(`SELECT task_name, enabled FROM _emdash_cron_tasks WHERE plugin_id = '${PLUGIN}'`);
  assert.ok(disabledCron.every((task) => !task.enabled), JSON.stringify(disabledCron));
  const disabledRoute = await admin.post(`${API}/bulk-status`, {});
  const heldDisabled = snapshot();
  await sleep(75_000);
  assert.deepEqual(changedParts(heldDisabled, snapshot()).filter((part) => part !== 'cron'), []);
  for (const image of [E, F, G, H]) {
    const active = activeRevision(image.id);
    assert.equal((await fetchBytes(fileUrl(image.storageKey))).sha256, active.sha256);
  }
  passed('disable stops work and images keep serving', { pluginRouteWhileDisabled: disabledRoute.status, cron: disabledCron });
  expectOk(await admin.post(`/_emdash/api/admin/plugins/${PLUGIN}/enable`, {}), 'enable');
  const continued = await waitFor('run after re-enable', async () => {
    const current = await route('bulk-status', {});
    return current.run?.runId === restoreRun.run.runId && current.run.status === 'complete' ? current.run : null;
  }, { timeoutMs: 360_000, intervalMs: 5_000 });
  assert.equal(continued.counts.restored, 3, JSON.stringify(continued));
  for (const image of [F, G, H]) assert.equal((await fetchBytes(fileUrl(image.storageKey))).sha256, image.originalSha);
  passed('re-enable continues the run', { runId: continued.runId, counts: continued.counts });

  // 6. The sandboxed edition registered instead: same data, read-only, no apply routes.
  const beforeSandbox = snapshot();
  await restartAs('sandbox', 'sandboxed-format edition in process');
  await logIn(admin, adminPasskey);
  const sandboxApply = await admin.post(`${API}/apply`, { mediaId: J.id });
  const sandboxBulk = await admin.post(`${API}/bulk-start`, { kind: 'apply', mediaIds: [J.id] });
  assert.equal(sandboxApply.status, 404);
  assert.equal(sandboxBulk.status, 404);
  const sandboxPage = JSON.stringify(await route('admin', { type: 'page_load', page: '/report' }));
  assert.ok(!sandboxPage.includes('apply_image') && !sandboxPage.includes('bulk_apply'), 'the sandboxed report offers apply');
  assert.deepEqual(changedParts(beforeSandbox, snapshot()).filter((part) => !['pluginStorage', 'pluginOptions', 'cron'].includes(part)), []);
  passed('sandboxed edition stays read-only', { applyRoute: sandboxApply.status, bulkStartRoute: sandboxBulk.status });

  // 7. Rollback: optimize one image, unregister the plugin, keep serving, restore with the host alone.
  await restartAs('native', 'native edition again');
  await logIn(admin, adminPasskey);
  const optimizedI = await route('apply', { mediaId: I.id });
  assert.equal(optimizedI.outcome, 'optimized');
  const iOptimized = activeRevision(I.id);
  const rowsBeforeRemoval = pluginRows();
  await restartAs('none', 'plugin unregistered');
  await logIn(admin, adminPasskey);
  assert.equal((await admin.post(`${API}/apply`, { mediaId: J.id })).status, 404);
  for (const image of Object.values(images)) {
    // Media never replaced has no revision yet: it serves the uploaded file.
    const expected = activeRevision(image.id)?.sha256 ?? image.originalSha;
    const got = await fetchBytes(fileUrl(image.storageKey));
    assert.equal(got.status, 200);
    assert.equal(got.sha256, expected);
  }
  assert.equal((await fetchBytes(fileUrl(I.storageKey))).sha256, iOptimized.sha256);
  await stopSite();
  const recoveryScript = `
    import { openSafeMediaRecovery } from 'emdash/media/safe-recovery';
    const recovery = await openSafeMediaRecovery(${JSON.stringify({ databasePath: paths.database, uploadsDirectory: paths.uploads, privateDirectory: paths.private })});
    const listed = await recovery.listRestorableOriginals(${JSON.stringify(I.id)});
    const restored = await recovery.restoreMedia(${JSON.stringify(I.id)});
    await recovery.close();
    console.log(JSON.stringify({ listed, restored }));
  `;
  // Under systemd, as the site user in a unit with the site's caps and sandbox, so that what it
  // writes belongs to the site user.
  const recovery = hosted
    ? hosted.recover(recoveryScript)
    : execFileSync(process.execPath, ['--input-type=module', '-e', recoveryScript], { cwd: paths.site, encoding: 'utf8' });
  const recovered = JSON.parse(recovery.trim().split('\n').at(-1));
  await restartAs('none', 'plugin unregistered, after host recovery');
  assert.equal((await fetchBytes(fileUrl(I.storageKey))).sha256, I.originalSha);
  assert.deepEqual(pluginRows(), rowsBeforeRemoval, 'plugin data changed while unregistered');
  passed('rollback: unregistered plugin, images serve, host recovery restores byte-exact', {
    mediaId: I.id,
    optimizedSha256: iOptimized.sha256,
    restoredSha256: I.originalSha,
    recoveryListed: Array.isArray(recovered.listed) ? recovered.listed.length : recovered.listed,
    recoveryResult: recovered.restored?.ok ?? recovered.restored?.status ?? null,
  });

  // 8. Reinstall: the plugin finds its data; the host's restore is not undone or claimed.
  await restartAs('native', 'native edition reinstalled');
  await logIn(admin, adminPasskey);
  assert.deepEqual(pluginRows(), rowsBeforeRemoval);
  const afterRecovery = await route('restore', { mediaId: I.id });
  assert.equal(afterRecovery.outcome, 'nothing-to-restore', JSON.stringify(afterRecovery));
  assert.equal((await fetchBytes(fileUrl(I.storageKey))).sha256, I.originalSha);
  const finalE = await route('restore', { mediaId: E.id });
  assert.equal(finalE.outcome, 'restored');
  assert.equal((await fetchBytes(fileUrl(E.storageKey))).sha256, E.originalSha);
  assert.equal((await fetchBytes(fileUrl(K.storageKey))).sha256, K.originalSha);
  passed('reinstall keeps data continuity', { pluginRows: pluginRows(), restoreAfterHostRecovery: afterRecovery.outcome, laterRestore: finalE.outcome });
  if (hosted) passed('site data still belongs to the site user alone at the end', checkDataPermissions('at the end'));
  await stopSite();
  if (hosted) {
    passed('no unit of the run reached its memory limit', {
      unitsStarted: unitMemory.length,
      maxPeakBytes: Math.max(...unitMemory.map((memory) => memory.peakBytes ?? 0)),
      oomKills: unitMemory.reduce((sum, memory) => sum + (memory.events.oom_kill ?? 0), 0),
    });
  }

  return { host, patches, plugin, reuse: Boolean(reuse) };
}

/** The pilot's identity without rebuilding it, for `--reuse-packages`. */
function reusedHost(pilot) {
  const git = (...parameters) => build('git', parameters, { cwd: pilot }).trim();
  return { tarball: null, commit: git('rev-parse', 'HEAD'), tree: git('write-tree') };
}

function hardware() {
  if (hosted) {
    // The caps are the unit's, recorded under `runtime`; the host's own cgroup has none.
    return { cpuModel: cpus()[0]?.model ?? null, visibleCpus: cpus().length, totalMemoryBytes: totalmem(), platform: `${process.platform} ${process.arch}` };
  }
  const read = (path) => {
    try {
      return readFileSync(path, 'utf8').trim();
    } catch {
      return null;
    }
  };
  return {
    cpuModel: cpus()[0]?.model ?? null,
    visibleCpus: cpus().length,
    cgroupCpuMax: read('/sys/fs/cgroup/cpu.max'),
    cgroupMemoryMax: read('/sys/fs/cgroup/memory.max'),
    cgroupSwapMax: read('/sys/fs/cgroup/memory.swap.max'),
    totalMemoryBytes: totalmem(),
    platform: `${process.platform} ${process.arch}`,
  };
}

try {
  const { host, patches, plugin, reuse } = await main();
  const summarize = (items) => ({
    maxStaleResponses: Math.max(...items.map((item) => item.staleResponses)),
    maxMsToFresh: Math.max(...items.map((item) => item.msToFresh)),
    cacheControl: [...new Set(items.map((item) => item.cacheControl))],
  });
  const evidence = {
    timestamp: new Date().toISOString(),
    node: process.version,
    hardware: hardware(),
    source,
    profile: { ...qualifiedProfile, status: 'on the adapter qualified list: apply and restore allowed with no option set' },
    proxy: proxy
      ? { name: proxy.name, version: proxy.version, listens: 'loopback only', handlers: proxy.config.handlers, fileSystemRoots: proxy.config.roots.length, adminEndpoint: proxy.config.admin }
      : null,
    runtime: hosted
      ? {
          runner: 'systemd transient service under its own system user, one process per site',
          caps: hosted.expected,
          properties: hosted.properties.map((property) => property.replace(paths.data, '<data directory>')),
          units: unitMemory,
        }
      : { runner: 'child process in a container' },
    host: { emdashCommit: host.commit, emdashTree: host.tree, patches },
    plugin: { version: plugin.version, upgradeVersion: plugin.upgradeVersion },
    site: { adapter: '@astrojs/node standalone', database: 'SQLite (node:sqlite)', storage: 'local', binding: '127.0.0.1', dependencies: JSON.parse(await readFile(join(paths.site, 'package.json'), 'utf8')).dependencies },
    delivery: {
      events: delivery,
      direct: summarize(delivery.map((event) => event.direct)),
      transformed: summarize(delivery.map((event) => event.transformed)),
    },
    checks,
    durationSeconds: Math.round((Date.now() - started) / 1000),
  };
  // The site's tarball paths are local to the run; keep only the versions.
  evidence.site.dependencies = Object.fromEntries(Object.entries(evidence.site.dependencies).map(([name, value]) => [name, value.startsWith('file:') ? 'local tarball' : value]));
  if (source?.uncommittedChanges > 0) {
    // Evidence describes a commit; a checkout with other changes does not produce any.
    log(`All ${checks.length} checks passed (no evidence written: the checkout has ${source.uncommittedChanges} uncommitted changes).`);
  } else if (!args['no-evidence'] && !reuse) {
    const file = join(here, `site${hosted ? '-host' : ''}${proxied ? '-proxy' : ''}-latest.json`);
    await writeFile(file, `${JSON.stringify(evidence, null, 2)}\n`);
    log(`All ${checks.length} checks passed. Evidence: ${relative(repository, file)}`);
  } else {
    log(`All ${checks.length} checks passed (no evidence written).`);
  }
} catch (error) {
  console.error(error);
  console.error(`FAILED after ${checks.length} passed checks; no evidence written. Site log: ${join(paths.logs, 'site.log')}`);
  process.exitCode = 1;
} finally {
  await stopSite().catch(() => {});
  await proxy?.stop().catch(() => {});
}
